[changes-for-conference] - added libraries.h5p as part of the dependencies

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -4,9 +4,21 @@
 	dh $@ --no-parallel --verbose
 
 override_dh_auto_build:
+	if [ ! -f ./libraries.h5p ]; then \
+		echo "ERROR: Please create the libraries.h5p before building the debian package by running:"; \
+		echo "    ./pack_dependencies"; \
+		exit 1; \
+	fi
 	npm install
 	npm run build-bundle
 
 override_dh_auto_install:
-	install -d debian/bbb-plugin-template/var/www/bigbluebutton-default/assets/plugins/bbb-plugin-template
-	cp -r dist/* debian/bbb-plugin-template/var/www/bigbluebutton-default/assets/plugins/bbb-plugin-template
+	install -d debian/bbb-plugin-h5p/var/www/bigbluebutton-default/assets/plugins/bbb-plugin-h5p
+	install -d debian/bbb-plugin-h5p/var/www/bigbluebutton-default/assets/plugins/h5p
+	cp -r dist/* debian/bbb-plugin-h5p/var/www/bigbluebutton-default/assets/plugins/bbb-plugin-h5p
+	if [ -f libraries.h5p ] ; then \
+	unzip libraries.h5p -d debian/bbb-plugin-h5p/var/www/bigbluebutton-default/assets/plugins/h5p ; \
+	else \
+	echo "Please create the libraries.h5p before building the debian package by running:" ; \
+	echo "		./pack_dependencies" ; \
+	fi
